### ISSUE TITLE
Potential Python Frameworks for Web Page/App

### ISSUE THREAD

**Issue by LealAj** [JulyJun/sts-do-sth#2]
After a little bit of research, I saw that a lot of people seem to recommend bokeh or dash python libraries for data dashboards. Which, as I read, seems like what we want to do as we want to make it interactive (Rather than just serving up static .png's of the data visualization). I believe this will also take care of generating the charts as it is built with plotly.js for graphing.
Also, it seems that pandas and some version of SQL will still be best for the organizing, cleaning, and analyzing the data. 

I will include a few links that I thought looked promising, and we can chat the next time we are both free. I am not sure at the moment which will be better between bokeh and dash at the moment.

Dash - https://dash.plotly.com/interactive-graphing
Bokeh - https://bokeh.org/

Dash Example - https://towardsdatascience.com/dash-for-beginners-create-interactive-python-dashboards-338bfcb6ffa4

Bokeh Example - https://optimizemydayjob.medium.com/a-guide-to-interactive-python-dashboards-using-bokeh-2fc4904b20f2

**Comment by JulyJun** [comment]
Those libraries seem easy to control data and deploy.
I found 3 frameworks for Python web. Those are also easily followed with the given docs

flask: [https://github.com/pallets/flask?tab=readme-ov-file](https://github.com/pallets/flask?tab=readme-ov-file)
django: [https://github.com/django/django](https://github.com/django/django)
fastAPI: [https://fastapi.tiangolo.com/](https://fastapi.tiangolo.com/)
